apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset-dev
spec:
  selector:
    matchLabels:
      demotype: nginx-daemonset-demo-dev
  template:
    metadata:
      labels:
        demotype: nginx-daemonset-demo-dev
    spec:
      containers:
        - image: nginx
          name: nginx
      nodeSelector:
        env: dev
