apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: realdomain-ingress-resource
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: real.domain.net
    http:
      paths:
      - backend:
          serviceName: realdomain-nginx
          servicePort: 80
