apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["ls", "/foobar"]
      restartPolicy: Never
