apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:                     # a volume
    - name: secret-volume        # any name
      secret:                    # created from a secret
        secretName: secret-demo  # name of the secret
  containers:
    - image: busybox
      name: busybox
      command: ["/bin/sh"]
      args: ["-c", "sleep 600"]
      volumeMounts:              # mount the volume
        - name: secret-volume      # "any name"
          mountPath: /mydata       # here