apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - image: busybox
      name: busybox
      command: ["/bin/sh"]
      args: ["-c", "sleep 600"]
      env:
        - name: myusername       # define an env variable...
          valueFrom:             # from...
            secretKeyRef:        # a secret:
              name: secret-demo  # name of the secret
              key: username      # key in the secret