apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:                     # container needs a volume
    - name: demo                 # any name
      configMap:                 # created from a config map
        name: demo-configmap     # called demo-configmap
  containers:
    - image: busybox
      name: busybox
      command: ["/bin/sh"]
      args: ["-c", "sleep 600"]
      volumeMounts:              # mount the volume
        - name: demo               # "any name"
          mountPath: /mydata       # here