apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:                     # container needs a volume
    - name: mysql-config         # any name
      configMap:                 # created from a configmap
        name: mysql-demo-config  # called mysql-demo-config
        items:
          - key: my.cnf          # by saving the value of the my.cnf key
            path: my.cnf         # as this filename
  containers:
    - image: busybox
      name: busybox
      command: ["/bin/sh"]
      args: ["-c", "sleep 600"]
      volumeMounts:
        - name: mysql-config
          mountPath: /mydata