apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: nfs-demo-pvc
  containers:
    - image: busybox
      name: busybox
      command: ["/bin/sh"]
      args: ["-c", "sleep 600"]
      volumeMounts:
        - name: nfs-volume
          mountPath: /mydata
