#apiVersion: v1
#kind: Pod
#metadata:
#  name: gpu-pod
#spec:
#  containers:
#    - name: cuda-container
#      image: nvidia/cuda:9.0-cudnn7-devel
#      command: ["nvidia-smi"]
#      resources:
#        limits:
#          nvidia.com/gpu: 1
apiVersion: batch/v1
kind: Job
metadata:
  name: nvidia-smi
spec:
  template:
    spec:
      containers:
        - name: cuda-container
          image: nvidia/cuda:9.0-cudnn7-devel
          command: ["nvidia-smi"]
          resources:
            limits:
              nvidia.com/gpu: 1
      restartPolicy: Never
